from django.urls import path
from myapp import views 

urlpatterns = [
    path("inactive/",views.inactiveaccounts),
    path("base/", views.base),
    path("views.confirm_email_acc/", views.confirm_email_acc),
    path("login/", views.login),
    path("logout/", views.logout),
    path("passchange/", views.passchng),
    path("passchangedone/", views.passresetdone),
    path("passset/", views.passset),
    path("prfkdone/", views.prfkdone),
    path("prfkey/", views.prfkey),
    path("preset/", views.preset),
    path("supclosed/", views.supclosed),
    path("sup/", views.sup),
    path("vsent/", views.vsent),
    path("verequired/", views.verequired),
    path("calendar/", views.calendar),
    path("newc/", views.newc),
    path("chat/", views.chat),
    path("companies", views.company),
    path("fourzerothree/", views.fourzerothree),
    path("fourzerofour/", views.fourzerofour),
    path("fivezerozero/", views.fivezerozero),
    path("tempbase/", views.tempbase),
    path("detached_base/", views.detached_base),
    path("horizontal_base/", views.horizontal_base),
    path("landing/", views.landing),
    path("preloader_base/", views.preloader_base),
    path("two_column_base/", views.two_column_base),
    path("two_tone_icons_base/", views.two_tone_icons_base),
    path("vertical_base/", views.vertical_base),
    path("home/", views.home),
    path("about/", views.about),
    path("twocolumnsidebar/", views.twocolumnsidebar),
    # path("emailtemp/", views.emailtemp),
    path("social_feed/", views.social_feed),
    path("file_manager/", views.file_manager),
    path("widgets/", views.widgets),
]
